I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/script_timur_ch1.rpy", line 137, in script
    call screen thinkAbout
  File "renpy/common/000statements.rpy", line 670, in execute_call_screen
    store._return = renpy.call_screen(name, *args, **kwargs)
Exception: Screen thinkAbout is not known.


-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/script_timur_ch1.rpy", line 137, in script
    call screen thinkAbout
  File "C:\Users\angry\OneDrive\Рабочий стол\renpy\renpy\ast.py", line 2259, in execute
    self.call("execute")
  File "C:\Users\angry\OneDrive\Рабочий стол\renpy\renpy\ast.py", line 2241, in call
    return renpy.statements.call(method, parsed, *args, **kwargs)
  File "C:\Users\angry\OneDrive\Рабочий стол\renpy\renpy\statements.py", line 342, in call
    return method(parsed, *args, **kwargs)
  File "renpy/common/000statements.rpy", line 670, in execute_call_screen
    store._return = renpy.call_screen(name, *args, **kwargs)
  File "C:\Users\angry\OneDrive\Рабочий стол\renpy\renpy\exports.py", line 3333, in call_screen
    show_screen(_screen_name, _transient=True, *args, **kwargs)
  File "C:\Users\angry\OneDrive\Рабочий стол\renpy\renpy\display\screen.py", line 1220, in show_screen
    raise Exception("Screen %s is not known.\n" % (name[0],))
Exception: Screen thinkAbout is not known.


Windows-10-10.0.19045 AMD64
Ren'Py 8.1.2.23090503
Ты не один 0.1
Sun Oct 20 00:09:26 2024
