I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/script_timur_ch1.rpy", line 402, in script
    scene bg_grossery_shop with Blur
  File "game/script_timur_ch1.rpy", line 402, in <module>
    scene bg_grossery_shop with Blur
NameError: name 'Blur' is not defined

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/script_timur_ch1.rpy", line 402, in script
    scene bg_grossery_shop with Blur
  File "C:\Users\anago\OneDrive\Desktop\renpy-8.3.2-sdk\renpy\ast.py", line 1357, in execute
    paired = renpy.python.py_eval(self.paired)
  File "C:\Users\anago\OneDrive\Desktop\renpy-8.3.2-sdk\renpy\python.py", line 1209, in py_eval
    return py_eval_bytecode(code, globals, locals)
  File "C:\Users\anago\OneDrive\Desktop\renpy-8.3.2-sdk\renpy\python.py", line 1202, in py_eval_bytecode
    return eval(bytecode, globals, locals)
  File "game/script_timur_ch1.rpy", line 402, in <module>
    scene bg_grossery_shop with Blur
NameError: name 'Blur' is not defined

Windows-10-10.0.22631 AMD64
Ren'Py 8.3.2.24090902
Ты не один 0.1
Sat Dec  7 16:56:27 2024
